### ISSUE TITLE
css complier

### ISSUE THREAD

**Issue by leemason** [No-Half-Pixels/Fluent-Framework#19]
would be great to add a css complier to the framework options, when defining fields you could add

``` php
'css_map' => array(
    'selectors' => array(//array or string, imploded to comma separated later on
        'a.some-classname',
        '.another-classname'
    ),
    'properties' => array(//what the css will be, mapped as $key:$value; later on
        'font-size' => '[value]px'
    )
)
```

for fields with array values (fonts, multiselect, groups) we could use dot syntax with this function:

``` php
function assignArrayByPath(&$arr, $path, $value) {
    $keys = explode('.', $path);

    while ($key = array_shift($keys)) {
        $arr = &$arr[$key];
    }

    $arr = $value;
}
```

for the `[value]` short code like so `[value.font-family]`

then we could have a $obj->get_css(); function which loops through the fields, compiles the css and returns it for nice easy dynamic css.

ideally when processing we would assign each selector as an array index so instead of duplicating the css if there are multiple fields targeting the selector like this:

``` css
.class-name{
   font-family: $$;
}
.class-name{
   color: $$;
}
```

it would be 

``` css
.class-name{
    font-family: $$;
   color: $$;
}
```
